apiVersion: v1
kind: Service
metadata:
  name: pm1-homer-service
spec:
  selector:
    app: pm1-homer
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
  type: NodePort
